using System;
using UnityEngine;
using UnityEngine.InputSystem;

// This script is a simple character controller for Bear the main character.
[RequireComponent(typeof(CharacterController))] // Assure that the GameObject has a CharacterController component
public class SH_CharacterController : MonoBehaviour
{
    [Header("Movement settings")]
    public float moveSpeed = 5f; // Speed at which the character moves
    public float rotationSpeed = 10f; // Speed at which the character rotates to face the movement direction

    private CharacterController _controller;
    private Animator _animator;
    private Vector2 _moveInput;
    private Vector3 _currentMoveDirection;
    private IA_PlayerControls _inputActions; // Reference to the input actions generated by the Input System

    // This method is called when the script instance is being loaded. It initializes the CharacterController, Animator, and input actions.
    void Awake()
    {
        _controller = GetComponent<CharacterController>(); // Get the CharacterController component
        _animator = GetComponent<Animator>(); // Get the Animator component (if you have one for animations)
        _inputActions = new IA_PlayerControls(); // Initialize the input actions
    }

    // This method is called when the object becomes enabled and active. It enables the input actions and sets up callbacks for movement input.
    void OnEnable()
    {
        _inputActions.Player.Enable(); // Enable the input actions for the Mecha action map
        _inputActions.Player.Move.performed += ctx => _moveInput = ctx.ReadValue<Vector2>(); // Read the movement input when performed
        _inputActions.Player.Move.canceled += ctx => _moveInput = Vector2.zero; // Reset movement input when canceled
    }

    // This method is called when the object is disabled. It disables the input actions and updates animations to reflect the character's idle state.
    void OnDisable()
    {
        _inputActions.Player.Disable(); // Disable the input actions when the object is disabled
        UpdateAnimations(); // Update animations to reflect the character's idle state when input is disabled
    }

    // This method is called once per frame. It applies movement based on the current input and updates animations accordingly.
    void Update()
    {
        ApplyMovement(); // Apply movement based on the current input
        UpdateAnimations(); // Update animations based on the current movement direction
    }

    // This method applies movement to the character based on the current input and updates the character's rotation to face the movement direction.
    private void ApplyMovement()
    {
        _currentMoveDirection = new Vector3(_moveInput.x, 0, _moveInput.y); // Convert the 2D input into a 3D movement direction (X and Z axes)

        if (_currentMoveDirection.magnitude > 0.1f) // Check if there is significant input to move the character
        {
            _controller.Move(_currentMoveDirection * moveSpeed * Time.deltaTime); // Move the character using the CharacterController component
            Quaternion targetRotation = Quaternion.LookRotation(_currentMoveDirection); // Calculate the target rotation to face the movement direction
            transform.rotation = Quaternion.Slerp(transform.rotation, targetRotation, rotationSpeed * Time.deltaTime); // Smoothly rotate the character towards the target rotation
        }
    }

    // This method updates the animations based on the current movement direction. It sends the magnitude of the movement to the "Speed" parameter of the Animator.
    private void UpdateAnimations()
    {
        if (_animator != null) // Check if the Animator component is assigned before trying to update animations
        {
            float speed = _currentMoveDirection.magnitude * moveSpeed;
            _animator.SetFloat("Speed", speed); // Set the "Speed" parameter in the Animator to control animations based on movement speed
            Debug.Log($"Current Move Direction: {_currentMoveDirection}, Speed: {speed}"); // |||||||||||||||||||||||||||DEBUGGING PURPOSES ONLY||||||||||||||||||||||||||
        }
    }
}